package barev

VERSION_MAJOR :: 0
VERSION_MINOR :: 2
VERSION_PATCH :: 0
VERSION_PRERELEASE :: ""
VERSION :: "0.2.0"
PACKAGE_NAME :: "barev-odin"
PACKAGE_LICENSE :: "GPL-3.0-or-later"
MINIMUM_ODIN_VERSION :: "dev-2026-09"
